# Generated by Django 4.2.2 on 2023-06-09 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_menu_menu_item_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='menu_item_description',
        ),
    ]
